### ISSUE TITLE
行列の default major を column-major に修正

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#109]
distributed_matrixとlocalized_matrixで、Fortran標準のrokko::matrix_col_majorをデフォルトにする。

**Comment by t-sakashita** [comment]
LAPACKEなどC向けラッパーでも問題ないでしょうか。
念のため、確認させてください。> @wistaria

**Comment by wistaria** [comment]
もちろん、固有ベクトルが転置されます。「問題ない」というのはどういう意味でしょうか？

**Comment by t-sakashita** [comment]
LAPACKEでLAPACK_ROW_MAJORを指定された場合は、メモリを余分に使って行列が転置されるのですね。http://www.netlib.org/lapack/lapacke.html
その場合は、ユーザは、col(i)ではなく、row(i)メンバ関数で固有ベクトルを取得することになるんですね。
了解しました。

**Comment by t-sakashita** [comment]
デフォルトをcolumn-majorに変更しました。
68235033d13c8d33e3deed4f1f684e5e8cc98c0d

**Comment by wistaria** [comment]
多分違っていると思います。localized_martix の matrix_row_major / matrix_col_major と LAPACKE の LAPACK_ROW_MAJOR / LAPACK_COL_MAJOR の指定を合わせておけば、LAPACK_ROW_MAJOR / LAPACK_COL_MAJOR どちらの場合も「各列」にそれぞれの固有ベクトルが入ります。指定する major が異なっていれば、「各行」が固有ベクトルになります。

**Comment by wistaria** [comment]
ところで、ctest が全て PASS することは確認しましたか？

**Comment by t-sakashita** [comment]
ctestは全てPASSしています。
いつも、MacのClangでPASSするのを確認してからpushしています。
