### ISSUE TITLE
ParametersListsクラスを作る

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#128]
ALPSを元に、int型、double型、（文字列型も？）を渡すことができるParametersListsクラスを作って下さい。

使用例：
 * 固有値ソルバの収束判定に用いるepsilon、double型
 * 求める固有値の数の指定、int型
 * 前処理方法、文字列型

**Comment by wistaria** [comment]
Done in 0dc18c6b30040711f5db8fa8feaffdf348c4d457
