### ISSUE TITLE
module ファイルがインストールされていない

### ISSUE THREAD

**Issue by yomichi** [t-sakashita/rokko#133]
Fortran からRokko を `use rokko` として呼び出すために必要となる `*.mod` ファイルがインストールされない

`include` 直下に置くか、 `include/fortran` などのディレクトリにおいて、Fortran の時だけそこをinclude_path に含めるか

前者はとても簡単、後者のほうがスマート？

**Comment by wistaria** [comment]
EigenExa のインストール等でも include 直下に mod をインストールしています。
https://github.com/t-sakashita/rokko/blob/develop/3rd-party/install/EigenExa/EigenExa-2.2a.patch
同じで良いと思います。

**Comment by wistaria** [comment]
5579ad13c130d08ab7f71be1924d6e1810b67432 で対応済み
