### ISSUE TITLE
GCCでsample_fortran/dense/frank_mpi_set_global.f90がコンパイルエラー

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#134]
[ 97%] Building Fortran object sample_fortran/dense/CMakeFiles/sample_fortran_frank_mpi_set_global.dir/frank_mpi_set_global.f90.o
cd /Users/wistaria/build/Darwin-x86_64/rokko/sample_fortran/dense && /opt/local/bin/gfortran  -DBOOST_ALL_DYN_LINK=1 -DBOOST_ALL_NO_LIB=1 -fopenmp -O3 -I/Users/wistaria/build/Darwin-x86_64/rokko -I/Users/wistaria/Dropbox/Development/rokko -I/Users/wistaria/build/Darwin-x86_64/rokko/3rd-party/lapacke/include -I/Users/wistaria/Dropbox/Development/rokko/3rd-party/lapacke/include -I/Users/wistaria/Dropbox/Development/rokko/3rd-party/eigen3 -I/Users/wistaria/Dropbox/Development/rokko/rokko -I/Users/wistaria/build/Darwin-x86_64/rokko/rokko -I/opt/materiapps/boost/boost_1_55_0-1 -I/opt/local/include/openmpi-gcc49 -I/opt/materiapps/rokko/petsc-3.5.2-0/Release/include -I/opt/materiapps/rokko/slepc-3.5.3-0/Release/include -I/opt/materiapps/rokko/trilinos/Release/include -I/opt/local/lib/openmpi-gcc49    -c /Users/wistaria/Dropbox/Development/rokko/sample_fortran/dense/frank_mpi_set_global.f90 -o CMakeFiles/sample_fortran_frank_mpi_set_global.dir/frank_mpi_set_global.f90.o
/Users/wistaria/Dropbox/Development/rokko/sample_fortran/dense/frank_mpi_set_global.f90:59.61:

         call rokko_distributed_matrix_set_global(mat, i, j, value)
                                                             1
Error: Type mismatch in argument 'value' at (1); passed REAL(4) to REAL(8)
make[2]: *** [sample_fortran/dense/CMakeFiles/sample_fortran_frank_mpi_set_global.dir/frank_mpi_set_global.f90.o] Error 1
make[2]: Leaving directory `/Users/wistaria/build/Darwin-x86_64/rokko'
make[1]: *** [sample_fortran/dense/CMakeFiles/sample_fortran_frank_mpi_set_global.dir/all] Error 2
make[1]: Leaving directory `/Users/wistaria/build/Darwin-x86_64/rokko'
make: *** [all] Error 2
make: Leaving directory `/Users/wistaria/build/Darwin-x86_64/rokko'

**Comment by wistaria** [comment]
value を real で宣言しているのが問題。ちゃんと倍精度実数で定義しなければダメ

**Comment by t-sakashita** [comment]
realをdouble precisionに直した。
MacのOpenMPI+GNU4.9コンパイラで正常実行を確認。
47b0d267d8204fff5890eabac74bbddc8689adca

**Comment by wistaria** [comment]
倍精度実数を指定するのに
  real(8)
  real(c_double)
  real(kind=c_double)
  real(kind(1d0))
  double precision
など、いろいろな書き方が混在していて汚い。どれかに統一すべき。

**Comment by wistaria** [comment]
#136 に新規issue作成済み
