### ISSUE TITLE
Fortranでの倍精度実数の宣言の仕方を統一する

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#136]
現状、倍精度実数を指定するのに
  real(8)
  real(c_double)
  real(kind=c_double)
  real(kind(1d0))
  double precision
など、いろいろな書き方が混在していて汚い。どれかに統一すべき。

**Comment by t-sakashita** [comment]
Fortranでは、double precisionが正式なようだ。
http://www.nag-j.co.jp/fortran/FI_4.html

**Comment by t-sakashita** [comment]
defc7abaa30786d97b2bf82dfa0dd1dd401e3850

**Comment by wistaria** [comment]
まだぜんぜん統一されていないようですが、close してしまっていいんでしょうか？
また、後々のためにも、コーディングスタンダードを wiki にまとめといてください。

**Comment by t-sakashita** [comment]
* sample_fortranの中は統一した。9b56cdc722a3f22bd6d287288b2a8b25b0b06ae4
* tutorial/titpackのfortranは、オリジナルがreal(8)なので、そのまま
