### ISSUE TITLE
tutorial/C の拡張

### ISSUE THREAD

**Issue by yomichi** [t-sakashita/rokko#145]
- [ ] Rokko.c を~~sparse~~ parallel 版に書き換える
- [ ] ScaLAPACK.c を書く

できているけれど、Rokko 本体のビルドにコケたので、そちらが片付き次第コミットします

**Comment by wistaria** [comment]
想定している EigenExa のバージョンが知らないうちに 2.2b に上がっている？？？

**Comment by yomichi** [comment]
アップデートしたら通ったので、そうみたいです ＞ EigenExa
