### ISSUE TITLE
エルミート行列(複素)の対角化用インターフェースがほしい

### ISSUE THREAD

**Issue by rigarash** [t-sakashita/rokko#153]
2015-02-04の若手技術交流会の際も、 @yomichi と議論した話で、テンプレートパラメータの破壊的変更が必要、という結論になっております。

また、2015-02-23のスピン軌道ミーティングの際に、鈴木さんからこの機能への希望をもらいました。鈴木さんは、現在のインターフェースのままエルミート行列を投入し、結果がおかしくなって気づいたとのことでした。

**Comment by wistaria** [comment]
Duplicate with #139
