### ISSUE TITLE
boost::anyまたはboost::variantを使ったparametersクラスの実装の検討

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#154]
std::stringではなく、boost::anyやboost::variantを使って実装すると効率的か？
ただし、いずれの実装でも、値の元の型（int, double, string）を知ることはできない。  
元の型に変換して取り出したいときは、以下のように一つ一つ書かなければいけない。  
```
int block_size = params.get<int>("Block Size");
double tol = params.get<double>("Convergence Tolerance");
```

**Comment by t-sakashita** [comment]
Trilinosで使われているTeuchos::ParameterListは、boost::anyを元に書かれたクラスである。
http://trilinos.org/docs/dev/packages/teuchos/browser/doc/html/Teuchos__ParameterList_8hpp_source.html

**Comment by yomichi** [comment]
リンク切れてます

**Comment by yomichi** [comment]
あと、テンプレートメンバ関数として型キャスト演算子をオーバーロードすれば、最初にあるような例なら自動でテンプレート引数を推論してくれます。

https://gist.github.com/yomichi/3ff97a47132be9b899a7

**Comment by t-sakashita** [comment]
rokko::parametersをboost::anyを使って実装した。
メンバ関数に以下を追加
* type　mapの値（第２引数）の型をstd::type_infoで返す。
* get_string
b636981179865f20d401e6b3b139487ca4c2d2c2

**Comment by yomichi** [comment]
get の中でif 分岐して例外投げていますが、これやらないでもboost::any_cast の方でbad_cast 例外を投げてくれるので、そちらに完全に任せる（元通り、any_cast だけやる）か、あるいはもう少し例外に情報をもたせるかしたほうがいいと思います

**Comment by yomichi** [comment]
anasazi/core.hpp のsolver::diagonalized で、

    if (params.defined("routine")) {
      if ((params.type("routine") == typeid(std::string)) && params.type("routine") == typeid(const char*))
      throw "error: routine is not charatcters or string";
      routine_ = params.get_string("routine");
    }
    solvermanager_t* solvermanager = create_solver_manager(routine_);

こんな感じに文字列かどうかをチェックしていますが、数字が  `routine` の中にあったとしても、 `create_solver_manager` の方でより適切なエラーメッセージと共に除外できるので、このif 分岐は不要かと思います。

**Comment by yomichi** [comment]
コメントしていて気づいたんですが、Issue には対応するcommits が無いので、コードレビューするにはpull request の方がやりやすいっぽいですねー。
ソースコード片に注釈つけて、それをこのIssue の流れに直接表示できるので。

**Comment by t-sakashita** [comment]
### anasazi/core.hpp のsolver::diagonalizeの件
間違えていました。以下のように、修正しました。
```
if (params.defined("routine")) {
   if ((params.type("routine") != typeid(std::string)) && params.type("routine") != typeid(const char*))
      throw "error: routine must be charatcters or string.";
}
routine_ = params.get_string("routine");
solvermanager_t* solvermanager = create_solver_manager(routine_);
```
そもそも文字列かどうかを判断しているかをチェックしています。

**Comment by yomichi** [comment]
> any_cast
このgist でやっているのは、こうすることで `any_cast` にテンプレート引数を明示的に渡さずとも、コンパイラが受け取る変数の型から推論してくれますよ、ということです。どちらにせよ最初には変数の型を宣言する必要があるので、どうするかはある種のこだわりだと思います（ので、`boost::any` を生で使いたいので`any_cast` では毎回明示的に型を指定するのならそれでいいと思います）

> diag
文字列かどうかは`get_string` の中でチェックしているし（例外に載せる情報は少し違いますが）、
`type("routine") == typeid(int)` とかだった場合でも、`create_solver_manager` の方で（例えば' 42' とかいう名前のソルバはないので）落としてくれるんだし、いらないんじゃないかなー、というコメントでした。
まぁこれも拘りのレベルの話なのでどちらでもいいとは思います。

**Comment by t-sakashita** [comment]
ありがとうございます。

RokkoのparametersクラスのうちAnsazi関連のものを、TrilinosのTeuchos::ParametersListにそのまま渡すために、型変換をできるだけ自動で行えないかと考えていました。
やはり、typeidを使って以下のように、型ごとに場合分けするしかなさそうです。
```
if (params.type(key) == typeid(double)) {
   pl_.set(key, params.get<double>(key));
}
```

以下のように対処します。
* Anyクラスの使用は必要になったら再度検討
* 文字列型でなかったらエラーを出す仕様もそのまま。

**Comment by wistaria** [comment]
test/parameters がコアダンプします。どこかの時点でバグが入ったのだと思います。

$ ./parameters 
terminate called after throwing an instance of 'char const*'
Aborted (core dumped)

**Comment by t-sakashita** [comment]
修正しました。
15a1274c7ebe03984dcf2f0657411724566ec4a6
