### ISSUE TITLE
PETScのインストール時の環境変数PETSC_DIRとPETSC_ARCHの仕様変更への対応

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#159]
PETScのバージョン3.5.2から、make時にPETSC_DIRとPETS_ARCHを設定が必要になった。
（以前は、むしろ設定したらエラーになっていたはず。）

上記に対応するように、スクリプトを書き換える。

**Comment by t-sakashita** [comment]
Macの場合、PETS_ARCHは、リリースモードであっても、デバッグモードと同じで以下のようになる。
arch-darwin-c-debug

**Comment by t-sakashita** [comment]
## SLEPcのインストールについて
3rd-party/install/SLEPc/default.shは、以下のように書き換えないとエラーとなる。
書き換え前：```source $PREFIX_ROKKO/rokkoenv.d/petscvars.sh```
書き換え後：```source $PREFIX_ROKKO/petsc-3.5.2-0/petscvars.sh```

**Comment by wistaria** [comment]
前者は後者へのリンクですが、なぜエラーになるんでしょうか？

**Comment by t-sakashita** [comment]
インストールスクリプトmacos.shを更新
0d1150de24a375ff116cacae37e74e204ae69a16

**Comment by wistaria** [comment]
スクリプト本体に ScaLapack のバージョンを書いてはだめですよ > @t-sakashita

**Comment by t-sakashita** [comment]
修正しました。
48337f5e84a6f27c316ded69d11ff06cae255159
