### ISSUE TITLE
CMakeの変数名の統一

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#170]
固有値ソルバをおくディレクトリのCMake変数名は、ROKKO_SOLVER_DIRを廃止して、ROKKO_SOLVER_ROOTに統一したと思います。
以下でだけ、ROKKO_SOLVER_DIRが残っているのですが、変更して問題ないですか？
```
config/FindBoostSrc.cmake
9:  if(ROKKO_SOLVER_DIR)
10:    list(APPEND _PATHS ${ROKKO_SOLVER_DIR})
11:  endif(ROKKO_SOLVER_DIR)
```

**Comment by wistaria** [comment]
変更して大丈夫です。

**Comment by t-sakashita** [comment]
変更しました。

e623025f0217357fa891083cd2a67e2ae06b7f00
