### ISSUE TITLE
LAPACKEのmanglingで、どれが選ばれたかを出力する

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#173]
LAPACKEのコンパイル時に、Fortranのmangling（関数名にアンダースコアが付く位置）をCMake時に自動検出しています。
この過程や結果は、新しいアーキテクチャでリンクがうまくいかない場合等の手がかりになるように、画面出力した方が良いと思います。

**Comment by wistaria** [comment]
具体的にはどのような出力を期待していますか？
「3rd-party/lapacke/include/lapacke_mangling.h の中身を見よ」ではダメですか？
