### ISSUE TITLE
ELPAのインストールスクリプトの改訂

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#178]
ELPAはホームページからダウンロードできるようになりました。
http://elpa.rzg.mpg.de/elpa-tar-archive

**Comment by t-sakashita** [comment]
最新版に合わせて、ELPA用インターフェースを改訂した。

**Comment by t-sakashita** [comment]
ELPA-2015.11.001のconfigure時には、ScaLAPACKが要求される。
これは、ELPA自体はScaLAPACKに依存していないが、付属サンプルプログラムが依存しているため。
これにより、ELPAとRokkoインストールで別種類のScaLAPACKのライブラリがリンクされてしまう虞が出てくる。
だからといって、我々独自のCMakeLists.txtを作ることはできない。

より良い方法を検討したいが、しばらく様子見する。

**Comment by t-sakashita** [comment]
MacとIntel用は完成
8089d7c291681ddcc5724832e4acc021dd5e4bfb

**Comment by t-sakashita** [comment]
fx10.shを作ってみました。
ですが、富士通コンパイラを指定しても、そのチェックのため、Cのテストプログラムを実行しようとします。

以下のいずれかのように、改訂をお願いします。

* その実行を外す。
* そのチェックをバッチ処理で行うためにスクリプトを吐く
* そのチェックを、インタラクティブモードでも良いから行う。
* 元々、我々がCMakeLists.txtを用意する。

https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html

**Comment by t-sakashita** [comment]
d422f589f06098d3bc379ddcfe08ea4c7e663f84 -- config/FindELPA.cmake

**Comment by t-sakashita** [comment]
今村チームがクロスコンパイルに成功しているとのことです。
LAPACK以外の箇所でのOpenMPには非対応であることもわかっている。

**Comment by t-sakashita** [comment]
とりあえず、ELPA付属のconfigureをそのまま用いることにした。
8c3d915d43fb81139034a7bd9c71cd9690455bee

**Comment by wistaria** [comment]
elpa-2016.05.003の京・FX10でのコンパイルについて現状報告

1. configureを実行する前にMakefile.inの1087行目の
    ```
    build_lib = libelpa@SUFFIX@.la libelpatest@SUFFIX@.la 
    ```
   を
   ```
   build_lib = libelpatest@SUFFIX@.la libelpa@SUFFIX@.la 
   ```
   に修正

2. configure を以下のオプションで実行
    ```sh
    ./configure --host=sparc64v MPICC=mpifccpx CC=mpifccpx CFLAGS=-Kfast,openmp LDFLAGS=-SSL2BLAMP MPIFC=mpifrtpx FC=mpifrtpx FCFLAGS=-Kfast,openmp FCLDFLAGS=-SSL2BLAMP CXX=mpiFCCpx CXXFLAGS=-Kfast,openmp SCALAPACK_LDFLAGS=-SCALAPACK SCALAPACK_FCFLAGS=-SCALAPACK
    ```

現状では、最後のリンクのところで以下のエラーで止まる
```
 CCLD     elpa1_test_real_c_version
fccpx: fatal: -Kparallel option is not specified at linking of object files to which -Kparallel applied at compiling. The linking process is suspended.
 CCLD     elpa1_test_complex_c_version
fccpx: fatal: -Kparallel option is not specified at linking of object files to which -Kparallel applied at compiling. The linking process is suspended.
 CCLD     elpa2_test_real_c_version
fccpx: fatal: -Kparallel option is not specified at linking of object files to which -Kparallel applied at compiling. The linking process is suspended.
 CCLD     elpa2_test_complex_c_version
fccpx: fatal: -Kparallel option is not specified at linking of object files to which -Kparallel applied at compiling. The linking process is suspended.
```
-Kparallel が付いたライブラリと付いていないライブラリが混在しているのが理由と考えられるが、原因の特定まではできていない
