### ISSUE TITLE
rokko/elpa/elpa.cpp のコンパイルエラー

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#182]
$ make
[ 45%] Built target lapacke
[ 45%] Building CXX object rokko/CMakeFiles/rokko.dir/elpa/elpa.cpp.o
In file included from /home/wistaria/development/rokko/rokko/elpa/elpa.cpp:13:
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp: In member function ‘void rokko::detail::pd_solver_wrapper<SOLVER>::diagonalize(const std::string&, rokko::distributed_matrix<double, rokko::matrix_row_major>&, rokko::localized_vector<double, -0x00000000000000001>&, rokko::distributed_matrix<double, rokko::matrix_row_major>&, const rokko::parameters&, rokko::timer&) [with SOLVER = rokko::elpa::solver]’:
/home/wistaria/development/rokko/rokko/elpa/elpa.cpp:16:   instantiated from here
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp:70: error: no matching function for call to ‘rokko::elpa::solver::diagonalize(const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, rokko::distributed_matrix<double, rokko::matrix_row_major>&, rokko::localized_vector<double, -0x00000000000000001>&, rokko::distributed_matrix<double, rokko::matrix_row_major>&, const rokko::parameters&, rokko::detail::timer_base<rokko::detail::clock>&)’
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp: In member function ‘void rokko::detail::pd_solver_wrapper<SOLVER>::diagonalize(const std::string&, rokko::distributed_matrix<double, rokko::matrix_col_major>&, rokko::localized_vector<double, -0x00000000000000001>&, rokko::distributed_matrix<double, rokko::matrix_col_major>&, const rokko::parameters&, rokko::timer&) [with SOLVER = rokko::elpa::solver]’:
/home/wistaria/development/rokko/rokko/elpa/elpa.cpp:16:   instantiated from here
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp:75: error: no matching function for call to ‘rokko::elpa::solver::diagonalize(const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, rokko::distributed_matrix<double, rokko::matrix_col_major>&, rokko::localized_vector<double, -0x00000000000000001>&, rokko::distributed_matrix<double, rokko::matrix_col_major>&, const rokko::parameters&, rokko::detail::timer_base<rokko::detail::clock>&)’
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp: In member function ‘void rokko::detail::pd_solver_wrapper<SOLVER>::diagonalize(const std::string&, rokko::distributed_matrix<double, rokko::matrix_row_major>&, rokko::localized_vector<double, -0x00000000000000001>&, const rokko::parameters&, rokko::timer&) [with SOLVER = rokko::elpa::solver]’:
/home/wistaria/development/rokko/rokko/elpa/elpa.cpp:16:   instantiated from here
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp:81: error: no matching function for call to ‘rokko::elpa::solver::diagonalize(const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, rokko::distributed_matrix<double, rokko::matrix_row_major>&, rokko::localized_vector<double, -0x00000000000000001>&, const rokko::parameters&, rokko::detail::timer_base<rokko::detail::clock>&)’
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp: In member function ‘void rokko::detail::pd_solver_wrapper<SOLVER>::diagonalize(const std::string&, rokko::distributed_matrix<double, rokko::matrix_col_major>&, rokko::localized_vector<double, -0x00000000000000001>&, const rokko::parameters&, rokko::timer&) [with SOLVER = rokko::elpa::solver]’:
/home/wistaria/development/rokko/rokko/elpa/elpa.cpp:16:   instantiated from here
/home/wistaria/development/rokko/rokko/parallel_dense_solver.hpp:86: error: no matching function for call to ‘rokko::elpa::solver::diagonalize(const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, rokko::distributed_matrix<double, rokko::matrix_col_major>&, rokko::localized_vector<double, -0x00000000000000001>&, const rokko::parameters&, rokko::detail::timer_base<rokko::detail::clock>&)’
make[2]: *** [rokko/CMakeFiles/rokko.dir/elpa/elpa.cpp.o] Error 1
make[1]: *** [rokko/CMakeFiles/rokko.dir/all] Error 2
make: *** [all] Error 2

**Comment by t-sakashita** [comment]
ELPAのRokkoラッパーを更新していなかったのが、原因でした。
90a1dd0124b7159becb9f6cade6d8ce6707626fe

**Comment by wistaria** [comment]
rokko/elemental/elemental.cpp も同様なエラーで落ちます

**Comment by t-sakashita** [comment]
修正しました。
ba5a7a06d04646480ca4f169a5184ee31e8e45df
