### ISSUE TITLE
ソルバクラスの改訂

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#185]
現在、どのソルバも、serial_dense_solverクラスにまとめられている。

別々のクラスにする。
* serial_dense_ev：標準固有値問題
* serial_dense_gev：一般化固有値問題
* serial_dense_svd：特異値分解

**Comment by t-sakashita** [comment]
* initializeやfinalizeは、ライブラリ単位で行うべき。serial_dense_evとserial_dense_gevで別々に行うのは変。
どうすれば良いか。

**Comment by wistaria** [comment]
singleton オブジェクトを作って、initialize や finalize をそちらで行えば良いと思います。対応は次期バージョンにまわしましょう

**Comment by t-sakashita** [comment]
上記の改訂の前にまず、現在のソルバ群の名前を以下のように確定したいと思います。
* serial_dense_solver → serial_dense_ev
* parallel_dense_solver → parallel_dense_ev
* parallel_sparse_solver → parallel_sparse_ev
確認と改訂作業をお願いします。 @wistaria

**Comment by t-sakashita** [comment]
* serial
* parallel

* dense
* sparse

* ev
* svd
* qr
* lu

**Comment by t-sakashita** [comment]
8733b987481602f794d44841aa51ae3209386640
