### ISSUE TITLE
phiへの固有値ソルバのインストール

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#189]
Intelコンパイラ一式を入れ替えたので、固有値ソルバも全て再インストールしました。
インストール先は、`/home/materiapps/rokko_solvers`です。
以前のソルバのインストール先`/home/materiapps/rokko`は、そのまま残しています。

そのうち、Rokko本体もMateriAppsの共通のディレクトリにインストールすることになると思います。
phiに限らず、以下のようなディレクトリの使い分けを提案します。
* `/home/materiapps/rokko`：　Rokko本体のインストール先
* `/home/materiapps/rokko_solvers`（またはもっと良いディレクトリ名）：　Rokkoで使う固有値ソルバのインストール先

いかがでしょうか。 @wistaria

**Comment by t-sakashita** [comment]
phiへのインストール方法を、暫定的にまとめておきました。
https://github.com/t-sakashita/rokko/wiki/RokkoCMakeGeneratorExample

**Comment by wistaria** [comment]
phi の /home/materiapps/rokko のソルバーは 6/26 頃に全て再インストール済み。(rokko/3rd-party/install/check_version.sh でインストールされたバージョンとインストール日が確認できます) 何かインストールに問題があったでしょうか？

ソルバーも rokko も同じ /home/materiapps/rokko にインストールしたので良いと思います。実際 zetta はそのようにしています。

**Comment by t-sakashita** [comment]
再インストールはされたいないと、勘違いしていました。
Rokkoの本体のインストール先についても、了解しました。
