### ISSUE TITLE
num_solvers(), solvers(), default_solver() の  Fortran 版

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#204]

**Comment by t-sakashita** [comment]
`default_solver()`は実装
fcfc7de493e502eff605074a26f26739f44f2380

**Comment by t-sakashita** [comment]
1434dd3a2d293330a40cd9521c7a886c4e76a150
`solvers()`で使用する文字列には、自作の`type(string)`を用いた。
この`string`は、今のところ、character(len=:), allocatable :: str`である。これに未対応のコンパイラでは動かない。
