### ISSUE TITLE
C bindingでのRokkoオブジェクトの引数の型

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#210]
たとえば、rokko_parallel_dense_solverのコンストラクタやデストラクタのC bindingは、ポインタ型rokko_parallel_dense_solver*を引数にとる必要がある。
```
void rokko_parallel_dense_solver_construct(rokko_parallel_dense_solver* solver, const char* solver_name, int argc, char** argv);
void rokko_parallel_dense_solver_destruct(rokko_parallel_dense_solver* solver) {
```

一方、他のメンバ関数の引数としては、rokko_parallel_dense_solverは値渡し（ポインタ渡しでない）にもできる。
```
struct rokko_parameters rokko_parallel_dense_solver_diagonalize_distributed_matrix(struct rokko_parallel_dense_solver* solver,
  struct rokko_distributed_matrix* mat, struct rokko_localized_vector* eigvals,
  struct rokko_distributed_matrix* eigvecs);
```
なぜなら、rokko_parallel_dense_solverの中身は、void型ポインタからなる構造体であるため、値渡しでも、rokko_parallel_dense_solverクラスを操作することはできるからである。

値渡しにする利点：
* 呼び出すユーザが&をつける引数の数が減る。
* LAPACKEとの一貫性（LAPACKEの関数では、中で書き換えられない変数は、全て値渡しです。）

値渡しにする欠点：
* メンバ関数とコンストラクタ＆デストラクタのbinding関数の間で、一貫性がなくなる。
* voidポインタ１個分とはいえ、値のコピーのオーバーヘッドがある。

私としては、値渡しにできるものは、値渡しに統一した方が良いと思います。
いかがでしょうか。

**Comment by wistaria** [comment]
値渡しで良いと思います

**Comment by t-sakashita** [comment]
逐次密行列ソルバ、疎行列ソルバは終了
2a2d62a40ae1252613a38922ce850ea1bcef4990

**Comment by t-sakashita** [comment]
destruct関数では、deleteした後に、ヌルポインタ（C++では"0"）を収納する。

**Comment by t-sakashita** [comment]
fb17ba4f9afd810261df370dec84ecf59ca8eef1

**Comment by t-sakashita** [comment]
C bindingによっているFortran bindingも改訂した。（改訂していなかったから、Segfaultが起こっていた。）
2a3e27f64f1edec6a321e92ff1c3e3d845632848
