### ISSUE TITLE
Pythonバインディングの改訂

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#248]
Rokkoの改訂に合わせて整備する。

**Comment by yomichi** [comment]
python バインディングを有効にすると `rokko_ext.cpp` でビルドエラーが出るんですが、それも含めた改定という話ですか？

**Comment by t-sakashita** [comment]
はい、そうです。
よろしくお願いします。 @wistaria

**Comment by yomichi** [comment]
32f76ae
厄介なのでデフォルトでOFF にしました。

バインディングが直った暁にはこちらも修正ください。

**Comment by t-sakashita** [comment]
`mapping_bc`のPythonバインディングの作成。C bindingの上に作る。

**Comment by t-sakashita** [comment]
`default_mapping`を使用する例題プログラムを作成する。

**Comment by t-sakashita** [comment]
`return_value_policy<boost::python::return_opaque_pointer>()`を使うとポインタを返せることが分かった。
ビルドは通るが、segfaultが起こる。

**Comment by t-sakashita** [comment]
疎行列向けソルバのPython bindingを作成する。

**Comment by t-sakashita** [comment]
まずは、簡単のため、`parameters`なしの場合。

**Comment by t-sakashita** [comment]
以下のMPI並列版の密行列のように、Python側のMPIコミュニケータを変換して渡すようにしないと駄目か？
```
wrap_rokko_grid(boost::python::object comm, int grid_major) {
    boost::python::object comm_func = comm.attr("py2f");
    boost::python::object comm_f_obj = comm_func();
    int comm_f = boost::python::extract<int>(comm_f_obj);
    raw = new rokko_grid();
    rokko_grid_construct_f(raw, comm_f, grid_major);
  }
```

**Comment by t-sakashita** [comment]
疎行列向けソルバのPython bindingの改訂が終了。
fa163cf707bdb5a77846f6da0450d1020cf3a22b

**Comment by t-sakashita** [comment]
密行列向けソルバのPython bindingのPython bindingで`parameters`を受け渡しできるようにする。

**Comment by t-sakashita** [comment]
`diagonalize`関数のオーバーロード

**Comment by t-sakashita** [comment]
`diagonalize`関数の引数に`parameters`が含まれていない場合の自動オーバーロード

**Comment by t-sakashita** [comment]
`distributed_mfree`のバインディングの作成
