### ISSUE TITLE
PETScでWarningが出る

### ISSUE THREAD

**Issue by rigarash** [t-sakashita/rokko#276]
In file included from /srv/git/rokko/rokko/slepc/slepc.cpp:14:0:
/srv/git/rokko/rokko/slepc/core.hpp: In member function ‘void rokko::slepc::solver::eigenvector(int, double*) cons ’:
/srv/git/rokko/rokko/slepc/core.hpp:227:5: warning: ‘PetscErrorCode MatGetVecs(Mat, _p_Vec**, _p_Vec**)’ is deprecated [-Wdeprecated-declarations]
     MatGetVecs(*A, NULL, &evec_r);
     ^
In file included from /usr/include/slepc/slepcsys.h:44:0,
                 from /usr/include/slepc/slepcst.h:26,
                 from /usr/include/slepc/slepceps.h:26,
                 from /srv/git/rokko/rokko/slepc/distributed_crs_matrix.hpp:20,
                 from /srv/git/rokko/rokko/slepc/core.hpp:16,
                 from /srv/git/rokko/rokko/slepc/slepc.cpp:14:
/usr/include/petsc/petscmat.h:557:76: note: declared here
 PETSC_DEPRECATED("Use MatCreateVecs()") PETSC_STATIC_INLINE PetscErrorCode MatGetVecs(Mat mat,Vec *x,Vec *y) {retu
                                                                            ^
In file included from /srv/git/rokko/rokko/slepc/slepc.cpp:14:0:
/srv/git/rokko/rokko/slepc/core.hpp:227:5: warning: ‘PetscErrorCode MatGetVecs(Mat, _p_Vec**, _p_Vec**)’ is deprecated [-Wdeprecated-declarations]
     MatGetVecs(*A, NULL, &evec_r);
     ^
In file included from /usr/include/slepc/slepcsys.h:44:0,
                 from /usr/include/slepc/slepcst.h:26,
                 from /usr/include/slepc/slepceps.h:26,
                 from /srv/git/rokko/rokko/slepc/distributed_crs_matrix.hpp:20,
                 from /srv/git/rokko/rokko/slepc/core.hpp:16,
                 from /srv/git/rokko/rokko/slepc/slepc.cpp:14:
/usr/include/petsc/petscmat.h:557:76: note: declared here
 PETSC_DEPRECATED("Use MatCreateVecs()") PETSC_STATIC_INLINE PetscErrorCode MatGetVecs(Mat mat,Vec *x,Vec *y) {retu
                                                                            ^

**Comment by t-sakashita** [comment]
petsc3.6未満で使用されていた命令を除けば良い。

**Comment by t-sakashita** [comment]
5cdae1fc04b768ac449c405a3ccc923bac787529
be688473a8be3a7424efe1bfdabb00e4843041bb
