### ISSUE TITLE
CMakeのFindの整理

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#312]
以下は、CMakeに付属のものを使う。
* FindBoost.cmake（必要なソースだけとってくるFindBoostSrc.cmakeの機能は、何らかの形で残す。）
* FindLapack.cmake
* FindPython.cmake

**Comment by wistaria** [comment]
issue-312ブランチで作業中 https://github.com/t-sakashita/rokko/tree/issue-312

**Comment by wistaria** [comment]
#313

**Comment by t-sakashita** [comment]
「京」でBoostのインクルードディレクトリの設定がうまく行きません。
```
"/home/hp120283/k00377/development/rokko/rokko/factory.hpp", line 15: catastrophic error: cannot open source file "boost/noncopyable.hpp"
  #include <boost/noncopyable.hpp>
                                  ^
```

試してみてください。

**Comment by wistaria** [comment]
MateriApps Installer の boost インストールを修正しました。以下の手順で boost は正しく認識されると思います

# boost & cmake のインストール by MateriApps Installer

cd $HOME
wget -O - https://github.com/wistaria/MateriAppsInstaller/archive/master.tar.gz | tar zxf -
mkdir -p $HOME/materiapps $HOME/build
sh MateriAppsInstaller-master/00_env/fx10.sh
sh MateriAppsInstaller-master/25_boost/fx10.sh
sh MateriAppsInstaller-master/25_boost/link-fx10.sh
sh MateriAppsInstaller-master/30_cmake/fx10.sh
sh MateriAppsInstaller-master/30_cmake/link.sh

# rokko

. $HOME/materiapps/env.sh
cmake \\
  -DCMAKE_CXX_COMPILER=mpiFCCpx -DCMAKE_C_COMPILER=mpifccpx \\
  -DCMAKE_CXX_FLAGS="-Kfast -KPIC -Kopenmp -Xg -mt" \\
  -DCMAKE_C_FLAGS="-Kfast -KPIC -Kopenmp -Xg -mt" \\
  -DBOOST_ROOT=$BOOST_ROOT/Linux-s64fx \\
  -DCMAKE_EXE_LINKER_FLAGS="-SSL2" \\
  -DCMAKE_SHARED_LINKER_FLAGS="-SSL2" \\
  -DLAPACK_FOUND=TRUE -DSCALAPACK_FOUND=TRUE \\
  -DMPI_COMPILE_FLAGS="-lmpi" \\
  -DMPI_INCLUDE_PATH=$MPI_HOME/include/mpi/fujitsu \\
  -DMPI_LIBRARY=$MPI_HOME/lib64/libmpi.so \\
  -DMPI_EXTRA_LIBRARY=$MPI_HOME/lib64/libmpi.so \\
  -DBUILD_Fortran_BINDING=OFF \\
  $HOME/development/rokko
make
