### ISSUE TITLE
Internal wrappersを独立させる。

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#328]
Rokkoを以下の2つの階層に分離

[下部] 独立したinternal wrappers。（Rokko coreと名付けるかも。）
以下の順で、言語バインディングを階層化する。
1. Fortran (BLAS, LAPACK, ScaLAPACK, ELPA, EigenExa)
2. C (PETSc, SLEPc, ELPAのCバインディングはソルバに付属)
3. C++ (Elemental, Anasazi)

[上部] ソルバを選択できる仕組み。（これをRokkoと呼ぶかも。）
* Rokko coreのC++のラッパーに乗っている。
* このうえに、C, Fortranのラッパーを乗せる。

**Comment by t-sakashita** [comment]
exampleプログラムのディレクトリも、階層に対応して分離する。

**Comment by wistaria** [comment]
- [ ] blas
   - [ ] cblas
      - [ ] rokko::blas
- [ ] lapack
  - [ ] LAPACKE
    - [ ] rokko::lapack
- [ ] blacs
  - [ ] Cblacs
    - rokko::blacs
- [ ] pblas
  - [ ] cpblas
    - [ ] rokko::cpblas
- [ ] lapack
  - [ ] LAPACKE
    - [ ] rokko::lapack
- [ ] blacs
  - [ ] Cblacs
    - [ ] rokko::blacs
- [ ] pblas
  - [ ] cpblas
    - [ ] rokko::blas
- [ ] ELPA
  - [ ] celpa
    - [ ] rokko::elpa
- [ ] EigenExa
  - [ ] ceigenexa
    - [ ] rokko::eigenexa

**Comment by t-sakashita** [comment]
2020.05.001の正式リリースを待つ。

**Comment by t-sakashita** [comment]
ELPAのC++化が終了した。
07d24ee2371bd15f85d05d5b19ce373407105b85
