### ISSUE TITLE
ScaLAPACK等のラッパーでのFortranCInterfaceの採用

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#418]
FortranCInterfaceとは、manglingを解決するためのCMakeモジュールである。
これは、cblasとLAPACKEで使用されている。

https://cmake.org/cmake/help/latest/module/FortranCInterface.html

一方、ScaLAPACK、EigenExa等のラッパーでは、Rokko独自に定義したプリプロセッサROKKO_GLOBALを使用している。

**Comment by t-sakashita** [comment]
FortranCInterfaceへの置き換えの予定はありますか？
@wistaria

**Comment by wistaria** [comment]
現状、rokko/mangling.hの中で、lapacke_mangling.hを読み込んで、そこで定義されたマクロを使っているので、結局同じことではないでしょうか？

**Comment by t-sakashita** [comment]
確認してみると、そうでした。
