### ISSUE TITLE
Build fail with gcc

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#525]
gcc: 9.2

> [ 87%] Linking CXX executable sizes_for_all_libraries
> Undefined symbols for architecture x86_64:
>   "rokko::factory<rokko::detail::ps_ev_base>::instance_", referenced from:
>       mapping_1d_start_row_Test::TestBody()      in sizes_for_all_libraries.cpp.o
> ld: symbol(s) not found for architecture x86_64
> collect2: error: ld returned 1 exit status
> make[2]: *** [test/mapping_1d/sizes_for_all_libraries] Error 1

**Comment by wistaria** [comment]
see also https://github.com/t-sakashita/rokko/runs/510160588?check_suite_focus=true

**Comment by t-sakashita** [comment]
318de2fa855245090bd737da632c3262ba9480d1
