### ISSUE TITLE
ELPAのサイトにアクセスできなくなっている

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#587]
https://elpa.mpcdf.mpg.de

**Comment by t-sakashita** [comment]
Webサイトが復活した。

ダウンロードできるディレクトリ名は、以下に変更された。

https://elpa.mpcdf.mpg.de/software/tarball-archive/Releases

**Comment by t-sakashita** [comment]
96cce892cdc167eded4d73255e8010e632579bfb
