### ISSUE TITLE
"original"ソルバに対してdistributed_crs_matrixが登録されていない

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#588]
"original"ソルバに対してdistributed_crs_matrixが登録されていない(rokko/original/original.cpp)

```test_mapping_1d_sizes_for_all_libraries``` ```test_mapping_1d_various_num_local_rows_for_all_libraries``` が以下のエラーで実行失敗する
```
Error: unknown product: "original" (registered products: "anasazi", "slepc")
```

**Comment by wistaria** [comment]
以下のテストも同じ理由で失敗
```
test_sparse_laplacian_crs_mpi
test_sparse_laplacian_mfree_mpi
test_sparse_laplacian_crs_variable_local_rows_mpi
test_sparse_laplacian_mfree_variable_local_rows_mpi
test_sparse_tridiagonal_toeplitz_mfree_mpi
test_sparse_distributed_crs_symmetric_matrix_extract
```

**Comment by t-sakashita** [comment]
`original`ライブラリ用に、`distributed_crs_matrix`クラスを書いた。
22b6487531339e13ec46bf60d0b74d110fdc8232

**Comment by t-sakashita** [comment]
上記のエラーは、Mac上では解消しました。
