### ISSUE TITLE
格子からハミルトニアンを作る時に格子のインデックスが正しい範囲であるかどうかチェックする

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#60]
rokko/utility/heisenberg_hamiltonian.hpp
rokko/utility/xyz_hamiltonian.hpp
など

**Comment by t-sakashita** [comment]
XYZ模型に関しては、関数read_lattice_fileを用意
acf74000a5a351726ab29ddec561f6cb6d80a4bb
