### ISSUE TITLE
Actionsによるビルド失敗

### ISSUE THREAD

**Issue by t-sakashita** [t-sakashita/rokko#600]
GithubのActionでビルドが失敗した。
https://github.com/t-sakashita/rokko/actions/runs/4946144266/usage

そのエラーの詳細はどこ？

**Comment by wistaria** [comment]
runnerが古すぎたので ubuntu-latest に修正
https://github.com/t-sakashita/rokko/commit/4368798c4b4730b09348bbb2ed2ec2c3dd81646a
走り始めたが途中でfailする
https://github.com/t-sakashita/rokko/actions/runs/4988423978
