### ISSUE TITLE
エルミート行列のサポート

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#70]

**Comment by yomichi** [comment]
基本的にはメジャーと同じように選択肢として扱う

C などのラッパでは`rokko_localized_matrix_construct` などの関数の最後に、
major と同様に引数を渡して if 分岐

C++ では型テンプレートに追加

適当なときに一日ですべて終わらせないと辛いかも

**Comment by wistaria** [comment]
Duplicate with #139
