### ISSUE TITLE
distributed_crs_matrix::end_row() が最後の要素の「次」を指さないのは C++ 的には変

### ISSUE THREAD

**Issue by wistaria** [t-sakashita/rokko#96]
現状 distributed_crs_matrix::end_row() は最後の要素を指すのでループを

```
for (int i = mat.start_row(); i <= mat.end_row(); ++i) {
```

のように書かなければならない。C++ 的には非常に不自然

**Comment by t-sakashita** [comment]
直します。
Fortran bindingの方は、beginとendは1を足す。

**Comment by t-sakashita** [comment]
C++ラッパーを変更
ffc2e8545f94a8f07ff1f0d093f46d8e58fe5439

C Bindingでも問題なく使えるはず。

**Comment by t-sakashita** [comment]
C++/Cのexampleも変更
4df3e3aa383559482c858ab1f9179f2150b27c76

**Comment by t-sakashita** [comment]
ややこしい問題なので、合理的な対策をまとめた：
https://github.com/t-sakashita/rokko/wiki/IndicesProblems

**Comment by t-sakashita** [comment]
CRSにおいて、Fortran向けの添字に対応して関数を作る。
その使用例として、laplacian_crs_mpiを書く。

**Comment by t-sakashita** [comment]
Fotranバインディング（C言語風の添字）の関数名を変更
1255809c48f032237a7cf0b5b986da3df2b6e78e
